define igreen_sender = EmailSender("Iwan Green", "i.green")
define josborne_sender = EmailSender("Jeremy Osborne", "j.osborne")
define board_sender = EmailSender("{color=#3366BB}@Board{/color}", "board")
define rbell_sender = EmailSender("Robert Bell", "r.bell")
define wturnell_sender = EmailSender("William Turnell", "turnell")
define wt_scam_sender = EmailSender("Unknown", "turnellwillianmOFFICIAL@hotmail.com", False)
define hbarkin_sender = EmailSender("Henry Barkin", "h.barkin")
